name: CI/CD for Microservices

on:
  workflow_call:
    inputs:
      MICROSERVICE_NAME:
        required: true
        type: string
      NAMESPACE:
        required: true
        type: string
    secrets:
      GHCR_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rsantamaria01
          password: ${{secrets.GHCR_PASSWORD}}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ghcr.io/hsm-sanosoft/${{inputs.MICROSERVICE_NAME}}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: [self-hosted, Linux]
    needs: build-and-push
    steps:
      - name: Pull and Deploy Microservices
        run: |
          kubectl rollout restart deployment ${{inputs.MICROSERVICE_NAME}} -n ${{inputs.NAMESPACE}}
